#!/usr/bin/env python

import pygame
from pygame.locals import *

import gameengine

SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480

def main():
    
    pygame.init()
    screen = pygame.display.set_mode((SCREEN_WIDTH,SCREEN_HEIGHT))

    #bgImage = pygame.image.load('titlescreen.png').convert()
    engine = gameengine.GameEngine()

    print(engine)
    print(engine.state())
    #engine.state().handle_events(pygame.event.get())
 
    while engine.running:
        for event in pygame.event.get():
            if event.type == QUIT:
                return

        screen.fill((255,255,255))
        #screen.blit(bgImage,(0,0))
        engine.state().handle_events(pygame.event.get())
        pygame.display.flip()
 
if __name__ == '__main__':
    main()
