#!/usr/bin/env python

import pygame
from pygame.locals import *

SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480

def main():
    
    pygame.init()
    screen = pygame.display.set_mode((SCREEN_WIDTH,SCREEN_HEIGHT))

    bgImage = pygame.image.load('titlescreen.png').convert()
 
    while 1:
    	for event in pygame.event.get():
    		if event.type == QUIT:
    			return

		screen.fill((255,255,255))
		screen.blit(bgImage,(0,0))

		pygame.display.flip()
 
if __name__ == '__main__':
    main()
